schema_version = "1.0.0"
id = "Blockout"
version = "1.2.1"
name = "Blockout"
tagline = "Blockout"
maintainer = "ezelar.com"
type = "add-on"


# Optional link to documentation, support, source files, etc
# website = "https://github.com/niewinny/blockout"


tags = ["Modeling", "3D View", "Mesh"]
blender_version_min = "4.5.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

[permissions]
files = "Importing node group from disk"
